### ISSUE TITLE
client side lobs temporary file are deleted too early.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#247]
```
What steps will reproduce the problem?
1. create table including clob column on remote. like this.

create table ctest(id int, txt clob);

2. insert String over Constants.DEFAULT_MAX_LENGTH_CLIENTSIDE_LOB size.

insert into ctest values (1, 'xxxxx.....');

3. run this code.

    public static void main(String[] args) throws Exception {
        DriverManager.registerDriver(new Driver());
        Connection conn = DriverManager.getConnection("jdbc:h2:tcp://localhost/db", "user","password");
        ResultSet rs = conn.createStatement().executeQuery("select id,txt from ctest");
        List<Clob> list = new ArrayList<Clob>();
        while(rs.next()){
            list.add(rs.getClob(2));
        }
        for (Clob clob : list) {
            System.out.println(clob.getSubString(1, (int) clob.length()));
        }
        conn.close();
    }

4. exception was thrown.

Exception in thread "main" org.h2.jdbc.JdbcSQLException: レコード 
"D:\data\workspaces\workspace1\h2test\.lobs.db\1.temp.db" 
を読み込み中にファイルの破損を検出しました。可能な解��
�策: リカバリツールを使用してください
File corrupted while reading record: 
"D:\data\workspaces\workspace1\h2test\.lobs.db\1.temp.db". Possible solution: 
use the recovery tool [90030-144]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
    at org.h2.message.DbException.get(DbException.java:167)
    at org.h2.message.DbException.get(DbException.java:144)
    at org.h2.engine.SessionRemote.openFile(SessionRemote.java:613)
    at org.h2.value.ValueLob.getInputStream(ValueLob.java:610)
    at org.h2.value.ValueLob.getReader(ValueLob.java:603)
    at org.h2.jdbc.JdbcClob.getSubString(JdbcClob.java:153)
    at Sample.main(Sample.java:24)


What is the expected output? What do you see instead?

    When connection closed or transaction closed,  should delete temporary file. I think.
```

Original issue reported on code.google.com by `litail...@gmail.com` on 29 Oct 2010 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
The error message is strange, and I will change it. However what you want is 
currently not supported in the default mode. Apache Derby throws a better error 
message:

"You cannot invoke other java.sql.Clob/java.sql.Blob methods after calling the 
free() method or after the Blob/Clob's transaction has been committed or rolled 
back."

I just tested, and it seems that Oracle supports this feature.

H2 also support it, but only if you store LOBs in the database. To do that, you 
need to set the system property h2.lobInDatabase: 
System.setProperty("h2.lobInDatabase", "true"); - see also 
http://h2database.com/javadoc/org/h2/constant/SysProperties.html#h2.lobInDatabas
e - plus you need to re-create your database.
```

Original comment by `thomas.t...@gmail.com` on 30 Oct 2010 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your suggestion.

I tried using h2.lobInDatabase. version 1.2.137 and 1.2.144 .

But result is :

Exception in thread "main" org.h2.jdbc.JdbcSQLException: レコード 
"D:\data\workspaces\workspace1\h2test\h2.temp.c0b2274d6e47d1e4.0.temp.db" 
を読み込み中にファイルの破損を検出しました。可能な解��
�策: リカバリツールを使用してください
File corrupted while reading record: 
"D:\data\workspaces\workspace1\h2test\h2.temp.c0b2274d6e47d1e4.0.temp.db". 
Possible solution: use the recovery tool [90030-137]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
    at org.h2.message.DbException.get(DbException.java:167)
    at org.h2.message.DbException.get(DbException.java:144)
    at org.h2.engine.SessionRemote.openFile(SessionRemote.java:598)
    at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:265)
    at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:258)
    at org.h2.jdbc.JdbcClob.getSubString(JdbcClob.java:153)
    at Sample.main(Sample.java:24)

I runned that sample code to LocalDatabase(jdbc:h2:d:/temp/test). That works 
though it doesn't set h2.lobInDatabase. 

I read H2 source code(version 1.2.144). ResultRemote's close method close 
lobValue(at ResultRemote line 165). Then local temporary file are deleted.
I think JdbcResultSet shoud not close result in nextRow(). What's do you think?

```

Original comment by `litail...@gmail.com` on 1 Nov 2010 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
Related this issue, I have found wrong 
usage(DbException.getInvalidValueException). value and param are swapped.

version:1.2.144

JdbcClob(Line:147)
JdbcResultSet(Line:2854)
DateTimeUtils(Line:176)
DateTimeUtils(Line:163)
Database(Line:1795)

```

Original comment by `litail...@gmail.com` on 1 Nov 2010 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
> I think JdbcResultSet shoud not close result in nextRow(). What's do you 
think?

I think it would be better if H2 doesn't delete the temporary file. It would 
even be better if there is no temporary file. But I don't consider the current 
behavior a "bug". Keeping the temporary file is a new feature in my view. 
Please note that Apache Derby also works like this.

> wrong usage(DbException.getInvalidValueException). value and param are 
swapped.

Thanks! I will fix this problem.

```

Original comment by `thomas.t...@gmail.com` on 5 Nov 2010 at 9:39

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your reply. I understood it was not a bug. 
I will fix this issue in our dao framework.
```

Original comment by `litail...@gmail.com` on 5 Nov 2010 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
I'm resolving this issue as 'works for me'.

The plan is to change the LOB implementation so no temporary files are needed 
at all.
```

Original comment by `thomas.t...@gmail.com` on 12 Dec 2010 at 12:06
- Changed state: **WorksForMe**
