### ISSUE TITLE
Can observe the occasional double allocation error on slow machines in 1.0.72

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#25]
```
On a fairly slow Linux machine (embedded system) we sometimes get the
"index corrupted" double allocation error when opening a database after the
machine was restarted abruptly. This seems to be a timing issue (something
is not initialized in time for the check?) since the problem does not
happen every time with exactly the same set of database files. Opening the
same files on a faster Windows PC never displays the problem.

The call stack is:

db.index.db page 22 blocks 1408-1471
        at org/h2/message/Message.getInternalError (Message.java:129)
        at org/h2/store/DiskFile.setPageOwner (DiskFile.java:676)
        at org/h2/store/DiskFile.setBlockOwner (DiskFile.java:588)
        at org/h2/store/DiskFile.init (DiskFile.java:371)
        at org/h2/engine/Database.open (Database.java:537)

H2 Version: 1.0.72

```

Original issue reported on code.google.com by `a701...@gmail.com` on 30 May 2008 at 3:49

**Comment by GoogleCodeExporter** [comment]
```
I am sorry to say that, but it looks like a corruption problem. I am very 
interested
in analyzing and solving this problem. Corruption problems have top priority 
for me.
I have a few question:

- Could you send the full stack trace of the exception including message text?
- What is your database URL?
- You can find out if the database is corrupted when running SCRIPT TO 
'test.sql'
- With which version of H2 was this database created? You can find it out 
using: 
  select * from information_schema.settings where name='info.BUILD_ID'
- Did you use multiple connections?
- The first workarounds is: append ;RECOVER=1 to the database URL. 
  Does it work when you do this?
- The second workarounds is: delete the index.db file 
  (it is re-created automatically) and try again. Does it work when you do this?
- The third workarounds is: use the tool org.h2.tools.Recover to create 
  the SQL script file, and then re-create the database using this script. 
  Does it work when you do this?
- Do you use any settings or special features (for example, the setting LOG=0, 
  or two phase commit, linked tables, cache settings)?
- Is the application multi-threaded?
- On what operating system, file system, and virtual machine (java -version)?
- How big is the database?
- Is the database usually closed normally, or is process terminated forcefully 
  or the computer switched off?
- Is it possible to reproduce this problem using a fresh database 
  (sometimes, or always)?
- Are there any other exceptions (maybe in the .trace.db file)? 
  Could you send them to me please?
- Do you still have any .trace.db files, and if yes could you send them?
- Could you send me the .data.db file where this exception occurs?

Regards,
Thomas

```

Original comment by `thomas.t...@gmail.com` on 30 May 2008 at 4:07
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Hi Thomas, here is the information you requested:

We're using a file-based database:
jdbc:h2:c:\gsh\work\FUSION\dist\camera-sun\db\db

Our application is multi-threaded, but we get the exception on the first 
connection 
attempt, and there aren't any other threads trying to access the database. When 
we 
delete the index (db.index.db), we can successfully obtain the connection. Most 
likely the corruption happened because the database was not shut down 
gracefully. 

We don't get these errors very often, but they do appear once in a while. We 
now 
updated our connection url to use log=2, so, hopefully, this will prevent 
future 
index corruption errors. 

What we did find a little suspicious is that the exception was not always 
thrown 
when the same database files were used. That is, after we first got the 'index 
corrupted' exception we saved the corrupted db files, reran the application 
with 
them, but didn't get any errors that time. 

Exception:
Caused by: org.h2.jdbc.JdbcSQLException: General error: java.lang.Error: double
allocation in file C:\gsh\work\FUSION\dist\camera-sun\db\db.index.db page 82 
blocks 
5248-5311 [50000-72]
        at org.h2.message.Message.getSQLException(Message.java:92)
        at org.h2.message.Message.convert(Message.java:175)
        at org.h2.engine.Database.open(Database.java:535)
        at org.h2.engine.Database.<init>(Database.java:204)
        at org.h2.engine.Engine.openSession(Engine.java:58)
        at org.h2.engine.Engine.openSession(Engine.java:127)
        at org.h2.engine.Engine.getSession(Engine.java:110)
        at org.h2.engine.Session.createSession(Session.java:229)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:976)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:957)
        at org.h2.Driver.connect(Driver.java:57)
        at java.sql.DriverManager.getConnection(DriverManager.java:582)
        at java.sql.DriverManager.getConnection(DriverManager.java:185)
        at com.videoiq.fusion.camera.storage.DataSource.getNewConnection
(DataSource.java:226)
        ... 9 more
Caused by: java.lang.Error: double allocation in file 
C:\gsh\work\FUSION\dist\camera-
sun\db\db.index.db page 82 blocks 5248-5311
        at org.h2.message.Message.getInternalError(Message.java:129)
        at org.h2.store.DiskFile.setPageOwner(DiskFile.java:676)
        at org.h2.store.DiskFile.setBlockOwner(DiskFile.java:589)
        at org.h2.store.DiskFile.init(DiskFile.java:370)
        at org.h2.engine.Database.open(Database.java:521)
        ... 20 more


```

Original comment by `gshkol...@gmail.com` on 30 May 2008 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
To resolve this problem, I need some more information. Is this still a problem 
for
you? If you don't want to spend more time trying to find out what the root 
cause it
(which I would understand), then I suggest I close this issue for now, and you 
can
then re-open it or create a new issue once you have more information.

- You can find out if the database is corrupted when running SCRIPT TO 
'test.sql'
- With which version of H2 was this database created? You can find it out 
using: 
  select * from information_schema.settings where name='info.BUILD_ID'
- The first workarounds is: append ;RECOVER=1 to the database URL. 
  Does it work when you do this?
- The third workarounds is: use the tool org.h2.tools.Recover to create 
  the SQL script file, and then re-create the database using this script. 
  Does it work when you do this?
- Do you use any settings or special features (for example, the setting LOG=0, 
  or two phase commit, linked tables, cache settings)?
- On what operating system, file system, and virtual machine (java -version)?
- How big is the database?
- Is the database usually closed normally, or is process terminated forcefully 
  or the computer switched off?
- Is it possible to reproduce this problem using a fresh database 
  (sometimes, or always)?
- Are there any other exceptions (maybe in the .trace.db file)? 
  Could you send them to me please?
- Do you still have any .trace.db files, and if yes could you send them?
- Could you send me the .data.db file where this exception occurs?

Regards,
Thomas

```

Original comment by `thomas.t...@gmail.com` on 13 Jun 2008 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
I am closing this issue until there is more information. 
Please send a mail to re-open it.
```

Original comment by `thomas.t...@gmail.com` on 22 Jun 2008 at 3:48
- Changed state: **Invalid**
