### ISSUE TITLE
SQL doesn't return in 1.2.147, but returns fine in 1.1.118

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#267]
```
What steps will reproduce the problem?
(simple SQL scripts or simple standalone applications are preferred)
1. Create and in-memory database with these tables/indices:

create table TINY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,FROM_Z datetime not null,THRU_Z datetime not null,IN_Z datetime not 
null,OUT_Z datetime not null )
CREATE UNIQUE INDEX I_TINY_BALANCE_F ON TINY_BALANCE (BALANCE_ID,FROM_Z,IN_Z)
CREATE UNIQUE INDEX I_TINY_BALANCE_T ON TINY_BALANCE (BALANCE_ID,THRU_Z,OUT_Z)
create table NON_AUDITED_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,POS_INTEREST double,FROM_Z datetime not null,THRU_Z datetime not null )
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_F ON NON_AUDITED_BALANCE 
(BALANCE_ID,FROM_Z)
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_T ON NON_AUDITED_BALANCE 
(BALANCE_ID,THRU_Z)
create table AUDIT_ONLY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double not null,POS_INTEREST_M double not null,IN_Z datetime not null,OUT_Z 
datetime not null )
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_F ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,IN_Z)
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_T ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,OUT_Z)

2. insert 2000 rows into TINY_BALANCE, NON_AUDITED_BALANCE, AUDIT_ONLY_BALANCE 
each
3. following sql never returns in 1.2.147 (busy CPU, see stack trace), but 
works fine in 1.1.118 (takes < 3 seconds on my machine)

select t0.BALANCE_ID,t0.POS_QUANTITY_M,t0.POS_INTEREST_M,t0.IN_Z,t0.OUT_Z from 
AUDIT_ONLY_BALANCE t0 
    inner join  (select t1.POS_QUANTITY_M c0 from AUDIT_ONLY_BALANCE t1 
        inner join TINY_BALANCE t2 on t1.POS_INTEREST_M = t2.POS_QUANTITY_M 
        where  t1.OUT_Z = '9999-12-01 23:59:00.000' and t1.POS_QUANTITY_M > 5.0 
            and t2.FROM_Z <= '2003-05-01 00:00:00.000' and t2.THRU_Z > '2003-05-01 00:00:00.000' 
            and t2.OUT_Z = '9999-12-01 23:59:00.000' and t2.BALANCE_ID > 4999 
        group by t1.POS_QUANTITY_M) as d1 on t0.POS_INTEREST_M = d1.c0 
where  t0.POS_QUANTITY_M > 10.0 and t0.OUT_Z = '9999-12-01 23:59:00.000'


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system, file
system, and virtual machine?


Do you know a workaround? No

How important/urgent is the problem for you? Can't upgrade

In your view, is this a defect or a feature request? Defect

Please provide any additional information below.
I can't access google groups. Please reply via email.
```

Original issue reported on code.google.com by `mohammad...@gs.com` on 14 Dec 2010 at 3:47

**Comment by GoogleCodeExporter** [comment]
```
sample stack traces:

"main" prio=6 tid=0x01ce0c10 nid=0x1674 runnable [0x0007e000..0x0007fc14]
    at org.h2.value.Value.convertTo(Value.java:497)
    at org.h2.expression.Comparison.getValue(Comparison.java:228)
    at org.h2.expression.ConditionAndOr.getValue(ConditionAndOr.java:83)
    at org.h2.expression.Expression.getBooleanValue(Expression.java:180)
    at org.h2.command.dml.Select.queryGroup(Select.java:313)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:592)
    at org.h2.command.dml.Query.query(Query.java:257)
    at org.h2.command.dml.Query.query(Query.java:227)
    at org.h2.index.ViewIndex.find(ViewIndex.java:233)
    at org.h2.index.IndexCursor.find(IndexCursor.java:136)
    at org.h2.table.TableFilter.next(TableFilter.java:311)
    at org.h2.table.TableFilter.next(TableFilter.java:381)
    at org.h2.command.dml.Select.queryFlat(Select.java:498)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:597)
    at org.h2.command.dml.Query.query(Query.java:257)
    at org.h2.command.dml.Query.query(Query.java:227)
    at org.h2.command.CommandContainer.query(CommandContainer.java:78)
    at org.h2.command.Command.executeQuery(Command.java:132)
    - locked <0x14c24b28> (a org.h2.engine.Database)
    at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)

"main" prio=6 tid=0x01ce0c10 nid=0x1674 runnable [0x0007e000..0x0007fc14]
    at org.h2.table.TableFilter.next(TableFilter.java:373)
    at org.h2.table.TableFilter.next(TableFilter.java:323)
    at org.h2.command.dml.Select.queryGroup(Select.java:311)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:592)
    at org.h2.command.dml.Query.query(Query.java:257)
    at org.h2.command.dml.Query.query(Query.java:227)
    at org.h2.index.ViewIndex.find(ViewIndex.java:233)
    at org.h2.index.IndexCursor.find(IndexCursor.java:136)
    at org.h2.table.TableFilter.next(TableFilter.java:311)
    at org.h2.table.TableFilter.next(TableFilter.java:381)
    at org.h2.command.dml.Select.queryFlat(Select.java:498)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:597)
    at org.h2.command.dml.Query.query(Query.java:257)
    at org.h2.command.dml.Query.query(Query.java:227)
    at org.h2.command.CommandContainer.query(CommandContainer.java:78)
    at org.h2.command.Command.executeQuery(Command.java:132)
    - locked <0x14c24b28> (a org.h2.engine.Database)
    at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)
    - locked <0x14c24a60> (a org.h2.engine.Session)

```

Original comment by `mohammad...@gs.com` on 14 Dec 2010 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
Hi,

This is not a valid bug report sorry. I need the data as well to reproduce it. 
Example:


drop all objects;

create table TINY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,FROM_Z datetime not null,THRU_Z datetime not null,IN_Z datetime not 
null,OUT_Z datetime not null );
CREATE UNIQUE INDEX I_TINY_BALANCE_F ON TINY_BALANCE (BALANCE_ID,FROM_Z,IN_Z);
CREATE UNIQUE INDEX I_TINY_BALANCE_T ON TINY_BALANCE (BALANCE_ID,THRU_Z,OUT_Z);
create table NON_AUDITED_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,POS_INTEREST double,FROM_Z datetime not null,THRU_Z datetime not null );
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_F ON NON_AUDITED_BALANCE 
(BALANCE_ID,FROM_Z);
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_T ON NON_AUDITED_BALANCE 
(BALANCE_ID,THRU_Z);
create table AUDIT_ONLY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double not null,POS_INTEREST_M double not null,IN_Z datetime not null,OUT_Z 
datetime not null );
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_F ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,IN_Z);
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_T ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,OUT_Z);

insert into tiny_balance(BALANCE_ID, from_z, thru_z, IN_Z) select x, date 
'2003-01-01' + cast(x as int), date '2003-05-01' + cast(x as int), date 
'2003-01-01' + cast(x as int) from system_range(1, 2000);
insert into NON_AUDITED_BALANCE(BALANCE_ID, from_z, POS_QUANTITY_M) select x, 
date '2003-01-01' + cast(x as int), x / 100 from system_range(1, 2000);
insert into AUDIT_ONLY_BALANCE(BALANCE_ID, POS_INTEREST_M) select x, x / 100 
from system_range(1, 2000);

select t0.BALANCE_ID,t0.POS_QUANTITY_M,t0.POS_INTEREST_M,t0.IN_Z,t0.OUT_Z from 
AUDIT_ONLY_BALANCE t0 
    inner join  (select t1.POS_QUANTITY_M c0 from AUDIT_ONLY_BALANCE t1 
        inner join TINY_BALANCE t2 on t1.POS_INTEREST_M = t2.POS_QUANTITY_M 
        where  t1.OUT_Z = '9999-12-01 23:59:00.000' and t1.POS_QUANTITY_M > 5.0 
            and t2.FROM_Z <= '2003-05-01 00:00:00.000' and t2.THRU_Z > '2003-05-01 00:00:00.000' 
            and t2.OUT_Z = '9999-12-01 23:59:00.000' and t2.BALANCE_ID > 4999 
        group by t1.POS_QUANTITY_M) as d1 on t0.POS_INTEREST_M = d1.c0 
where  t0.POS_QUANTITY_M > 10.0 and t0.OUT_Z = '9999-12-01 23:59:00.000';


```

Original comment by `thomas.t...@gmail.com` on 14 Dec 2010 at 8:39

**Comment by GoogleCodeExporter** [comment]
```
insert into TINY_BALANCE (BALANCE_ID,POS_QUANTITY_M,FROM_Z,THRU_Z,IN_Z,OUT_Z) 
select
    (5000+x,x,date '2003-05-01 00:00:00.000',date '9999-12-01 23:59:00.000',date '2010-12-14 15:53:30.650',date '9999-12-01 23:59:00.000') from system_range(0,2000)

insert into NON_AUDITED_BALANCE 
(BALANCE_ID,POS_QUANTITY_M,POS_INTEREST,FROM_Z,THRU_Z) select 
(5000+x,x+1,x,date '2003-05-01 00:00:00.000',date '9999-12-01 23:59:00.000') 
from system_range(0,2000)

insert into AUDIT_ONLY_BALANCE 
(BALANCE_ID,POS_QUANTITY_M,POS_INTEREST_M,IN_Z,OUT_Z) select (5000+x,x+1,x,date 
'2010-12-14 15:44:17.880',date '9999-12-01 23:59:00.000')  from 
system_range(0,2000)


```

Original comment by `mohammad...@gs.com` on 14 Dec 2010 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
sorry about the missing data. I didn't know about system_range and didn't want 
to put too much junk into the report. hopefully the syntax is about right.

```

Original comment by `mohammad...@gs.com` on 14 Dec 2010 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Thanks! But now the query works for me, specially if I add ANALYZE before the 
query:

----------------

drop all objects;

create table TINY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,FROM_Z datetime not null,THRU_Z datetime not null,IN_Z datetime not 
null,OUT_Z datetime not null );
CREATE UNIQUE INDEX I_TINY_BALANCE_F ON TINY_BALANCE (BALANCE_ID,FROM_Z,IN_Z);
CREATE UNIQUE INDEX I_TINY_BALANCE_T ON TINY_BALANCE (BALANCE_ID,THRU_Z,OUT_Z);
create table NON_AUDITED_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double,POS_INTEREST double,FROM_Z datetime not null,THRU_Z datetime not null );
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_F ON NON_AUDITED_BALANCE 
(BALANCE_ID,FROM_Z);
CREATE UNIQUE INDEX I_NON_AUDITED_BALANCE_T ON NON_AUDITED_BALANCE 
(BALANCE_ID,THRU_Z);
create table AUDIT_ONLY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M 
double not null,POS_INTEREST_M double not null,IN_Z datetime not null,OUT_Z 
datetime not null );
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_F ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,IN_Z);
CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_T ON AUDIT_ONLY_BALANCE 
(BALANCE_ID,OUT_Z);

insert into TINY_BALANCE (BALANCE_ID,POS_QUANTITY_M,FROM_Z,THRU_Z,IN_Z,OUT_Z) 
select
5000+x,x,date '2003-05-01 00:00:00.000',date '9999-12-01 23:59:00.000',date 
'2010-12-14 15:53:30.650',date '9999-12-01 23:59:00.000' from 
system_range(0,2000);

insert into NON_AUDITED_BALANCE 
(BALANCE_ID,POS_QUANTITY_M,POS_INTEREST,FROM_Z,THRU_Z) select 
5000+x,x+1,x,date '2003-05-01 00:00:00.000',date '9999-12-01 23:59:00.000' from 
system_range(0,2000);

insert into AUDIT_ONLY_BALANCE 
(BALANCE_ID,POS_QUANTITY_M,POS_INTEREST_M,IN_Z,OUT_Z) select 
5000+x,x+1,x,date '2010-12-14 15:44:17.880',date '9999-12-01 23:59:00.000'  
from system_range(0,2000);

analyze;

select t0.BALANCE_ID,t0.POS_QUANTITY_M,t0.POS_INTEREST_M,t0.IN_Z,t0.OUT_Z from 
AUDIT_ONLY_BALANCE t0 
    inner join  (select t1.POS_QUANTITY_M c0 from AUDIT_ONLY_BALANCE t1 
        inner join TINY_BALANCE t2 on t1.POS_INTEREST_M = t2.POS_QUANTITY_M 
        where  t1.OUT_Z = '9999-12-01 23:59:00.000' and t1.POS_QUANTITY_M > 5.0 
            and t2.FROM_Z <= '2003-05-01 00:00:00.000' and t2.THRU_Z > '2003-05-01 00:00:00.000' 
            and t2.OUT_Z = '9999-12-01 23:59:00.000' and t2.BALANCE_ID > 4999 
        group by t1.POS_QUANTITY_M) as d1 on t0.POS_INTEREST_M = d1.c0 
where  t0.POS_QUANTITY_M > 10.0 and t0.OUT_Z = '9999-12-01 23:59:00.000';

----------------

I would need a test case that actually fails.
```

Original comment by `thomas.t...@gmail.com` on 14 Dec 2010 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
For me, the query works without analyze in 1.1.118, but does not return in 
1.2.147 (without analyze). Can you reproduce that? If so, do you not consider 
that a bug? If not, then we have a problem as it is fully reproducible in my 
setup.

```

Original comment by `mohammad...@gs.com` on 14 Dec 2010 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
It works for me even with version 1.2.147, using the H2 Console.
```

Original comment by `thomas.t...@gmail.com` on 14 Dec 2010 at 9:38
- Changed state: **WorksForMe**

**Comment by GoogleCodeExporter** [comment]
```
I figured out the issue. The inserted data are wrong. The inserts should be 
casting to TIMESTAMP not DATE. like this:

insert into TINY_BALANCE (BALANCE_ID,POS_QUANTITY_M,FROM_Z,THRU_Z,IN_Z,OUT_Z) 
select
5000+x,x,TIMESTAMP'2003-05-01 00:00:00.000',TIMESTAMP'9999-12-01 
23:59:00.000',TIMESTAMP'2010-12-14 15:53:30.650',TIMESTAMP'9999-12-01 
23:59:00.000' from system_range(0,2000);

insert into AUDIT_ONLY_BALANCE 
(BALANCE_ID,POS_QUANTITY_M,POS_INTEREST_M,IN_Z,OUT_Z) select 
5000+x,x+1,x,TIMESTAMP'2010-12-14 15:44:17.880',TIMESTAMP'9999-12-01 
23:59:00.000'  from system_range(0,2000);

```

Original comment by `mohammad...@gs.com` on 15 Dec 2010 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
package test;

import java.sql.*;
/*
 *******************************************************************************
 * File        : $Source:  $
 * Version     : $Revision: $
 * Date        : $Date: $
 * Modified by : $Author:  $
 *******************************************************************************
 */

public class H2Test
{
    private Connection con;

    public static void main(String[] args) throws Exception
    {
        new H2Test().run();
    }

    private void run() throws Exception
    {
        createDatabase();
        createTables();
        insertData();
        queryData();
    }

    private void queryData() throws Exception
    {
        System.out.println("starting query");
        long begin = System.currentTimeMillis();
        Timestamp infinity = Timestamp.valueOf("9999-12-01 23:59:00.000");
        Timestamp start = Timestamp.valueOf("2003-05-01 00:00:00.000");
        PreparedStatement stm = con.prepareStatement("select t0.BALANCE_ID,t0.POS_QUANTITY_M,t0.POS_INTEREST_M,t0.IN_Z,t0.OUT_Z from AUDIT_ONLY_BALANCE t0 \n" +
                "    inner join  (select t1.POS_QUANTITY_M c0 from AUDIT_ONLY_BALANCE t1 \n" +
                "        inner join TINY_BALANCE t2 on t1.POS_INTEREST_M = t2.POS_QUANTITY_M \n" +
                "        where  t1.OUT_Z = ? and t1.POS_QUANTITY_M > ? \n" +
                "            and t2.FROM_Z <= ? and t2.THRU_Z > ? \n" +
                "            and t2.OUT_Z = ? and t2.BALANCE_ID > ? \n" +
                "        group by t1.POS_QUANTITY_M) as d1 on t0.POS_INTEREST_M = d1.c0 \n" +
                "where  t0.POS_QUANTITY_M > ? and t0.OUT_Z = ?");
        stm.setTimestamp(1, infinity);
        stm.setDouble(2, 5.0);
        stm.setTimestamp(3, start);
        stm.setTimestamp(4, start);
        stm.setTimestamp(5, infinity);
        stm.setInt(6, 4999);
        stm.setDouble(7, 10.0);
        stm.setTimestamp(8, infinity);
        fullyExecute(stm);
        System.out.println("query finished in "+(System.currentTimeMillis() - begin));
    }

    private void insertData() throws Exception
    {
        executeUpdate("insert into TINY_BALANCE (BALANCE_ID,POS_QUANTITY_M,FROM_Z,THRU_Z,IN_Z,OUT_Z) select 5000+x,x,TIMESTAMP  '2003-05-01 00:00:00.000',TIMESTAMP  '9999-12-01 23:59:00.000',TIMESTAMP  '2010-12-14 15:53:30.650',TIMESTAMP  '9999-12-01 23:59:00.000' from system_range(0,2000)");
        executeUpdate("insert into AUDIT_ONLY_BALANCE (BALANCE_ID,POS_QUANTITY_M,POS_INTEREST_M,IN_Z,OUT_Z) select 5000+x,x+1,x,TIMESTAMP  '2010-12-14 15:44:17.880',TIMESTAMP  '9999-12-01 23:59:00.000'  from system_range(0,2000)");
        System.out.println("data inserted");
    }

    private void createTables() throws Exception
    {
        executeUpdate("create table TINY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M double,FROM_Z datetime not null,THRU_Z datetime not null,IN_Z datetime not null,OUT_Z datetime not null )");
        executeUpdate("CREATE UNIQUE INDEX I_TINY_BALANCE_F ON TINY_BALANCE (BALANCE_ID,FROM_Z,IN_Z)");
        executeUpdate("CREATE UNIQUE INDEX I_TINY_BALANCE_T ON TINY_BALANCE (BALANCE_ID,THRU_Z,OUT_Z)");
        executeUpdate("create table AUDIT_ONLY_BALANCE ( BALANCE_ID integer not null,POS_QUANTITY_M double not null,POS_INTEREST_M double not null,IN_Z datetime not null,OUT_Z datetime not null )");
        executeUpdate("CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_F ON AUDIT_ONLY_BALANCE (BALANCE_ID,IN_Z)");
        executeUpdate("CREATE UNIQUE INDEX I_AUDIT_ONLY_BALANCE_T ON AUDIT_ONLY_BALANCE (BALANCE_ID,OUT_Z)");
        System.out.println("tables created");
    }

    private void createDatabase() throws Exception
    {
        Class.forName("org.h2.Driver").newInstance();
        this.con = getConnection();
    }

    private Connection getConnection() throws Exception
    {
        return DriverManager.getConnection("jdbc:h2:mem:H2TEST", "sa", "");
    }

    private void executeUpdate(String sql) throws Exception
    {
        con.createStatement().executeUpdate(sql);
    }

    protected static void reportWarnings(PreparedStatement stm)
        throws SQLException
    {
        SQLWarning w = stm.getWarnings();
        while (w != null)
        {
            warn("SQL warning: ", w);
            w = w.getNextWarning();
        }
    }

    private static void warn(String s, SQLWarning w)
    {
        System.out.println("WARN: "+s);
        System.out.println(w.getClass().getName()+": "+w.getMessage());
        w.printStackTrace(System.out);
    }

    private static void readFullResultSet(ResultSet resultSet) throws SQLException
    {
        int count = 0;
        while(resultSet.next()) count++;
        resultSet.close();
        System.out.println("read "+count);
    }

    private static void fullyExecute(PreparedStatement ps) throws SQLException
    {
        int updateCount = -100;
        boolean isResultSet = ps.execute();
        while (updateCount != -1 || isResultSet)
        {
            if (isResultSet)
            {
                readFullResultSet(ps.getResultSet());
            }
            else
            {
                updateCount = ps.getUpdateCount();
            }
            isResultSet = ps.getMoreResults();
        }
    }

}

```

Original comment by `mohammad...@gs.com` on 15 Dec 2010 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
You don't need to open a new issue just because I changed the status of the 
first issue.
```

Original comment by `thomas.t...@gmail.com` on 26 Dec 2010 at 9:16
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Issue 268 has been merged into this issue.
```

Original comment by `thomas.t...@gmail.com` on 26 Dec 2010 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I don't think I will have time to further analyze it. It seems there is 
a table scan, I guest to analyze this as documented (create an index,...)
```

Original comment by `thomas.t...@gmail.com` on 17 Feb 2012 at 1:53
- Changed state: **WontFix**
