### ISSUE TITLE
Syntax error in SQL statement SET DATESTYLE TO 'ISO' (RHEL4+odbc+psycopg2+python-2.5)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#34]
```
What steps will reproduce the problem?
(simple SQL scripts or simple standalone applications are preferred)
-bash-3.00$ python
ActivePython 2.5.2.2 (ActiveState Software Inc.) based on
Python 2.5.2 (r252:60911, Mar 27 2008, 16:42:08)
[GCC 3.3.1 (SuSE Linux)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> conn=psycopg2.connect("dbname='db' user='user' password='pass' 
host='myhost' port='port'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.OperationalError: can't set datestyle to ISO

1.
2.
3.
server log returns 
Query
SET DATESTYLE TO 'ISO';
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement SET DATESTYLE 
TO 'ISO'; expected ISO; SQL statement:



Same error when connecting using aqua studio.


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system, file 
system, and virtual machine?



SELECT * FROM INFORMATION_SCHEMA.SETTINGS;
NAME   VALUE   
CREATE_BUILD 77 
CLUSTER '' 
DEFAULT_TABLE_TYPE 0 
WRITE_DELAY 500 
DEFAULT_LOCK_TIMEOUT 1000 
CACHE_SIZE 65536 
info.BUILD_ID 77 
info.VERSION_MAJOR 1 
info.VERSION_MINOR 0 
info.VERSION 1.0.77 (2008-08-16) 
property.java.runtime.version 1.6.0_01-b06 
property.java.vm.name Java HotSpot(TM) 64-Bit Server VM 
property.java.vendor Sun Microsystems Inc. 
property.os.name Linux 
property.os.arch amd64 
property.os.version 2.6.9-42.0.8.ELsmp 
property.sun.os.patch.level unknown 
property.file.separator / 
property.path.separator : 
property.line.separator 

property.user.country US 
property.user.language en 
property.user.variant   
property.file.encoding UTF-8 
EXCLUSIVE FALSE 
MODE PostgreSQL 
MULTI_THREADED 0 
MVCC FALSE 
QUERY_TIMEOUT 0 
LOB_FILES_IN_DIRECTORIES false 
h2.allowBigDecimalExtensions false 
h2.baseDir /projects/ 
h2.check true 
h2.check2 false 
h2.clientTraceDirectory trace.db/ 
h2.collatorCacheSize 32000 
h2.defaultMaxMemoryUndo 100000 
h2.emergencySpaceInitial 262144 
h2.emergencySpaceMin 65536 
h2.lobFilesInDirectories false 
h2.lobFilesPerDirectory 256 
h2.logAllErrors false 
h2.logAllErrorsFile h2errors.txt 
h2.maxFileRetry 16 
h2.maxQueryTimeout 0 
h2.lobCloseBetweenReads false 
h2.objectCache true 
h2.objectCacheSize 1024 
h2.objectCacheMaxPerElementSize 4096 
h2.optimizeIn true 
h2.optimizeInJoin false 
h2.optimizeMinMax true 
h2.optimizeSubqueryCache true 
h2.overflowExceptions true 
h2.recompileAlways false 
h2.redoBufferSize 262144 
h2.runFinalize true 
h2.scriptDirectory   
h2.serverCachedObjects 64 
h2.serverResultSetFetchSize 100 
h2.sortNullsHigh false 
CACHE_TYPE LRU 
info.FILE_DISK_WRITE 0 
info.FILE_DISK_READ 132 
info.FILE_INDEX_WRITE 1 
info.FILE_INDEX_READ 30 




Do you know a workaround?

How important/urgent is the problem for you?

Very - can't use product otherwise

In your view, is this a defect or a feature request?
defect 
Please provide any additional information below.



Thanks! 
```

Original issue reported on code.google.com by `effie.ba...@gmail.com` on 4 Sep 2008 at 4:56

**Comment by GoogleCodeExporter** [comment]
```
More details - 
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement SET DATESTYLE TO 
'ISO'; 
expected ISO; SQL statement:
SET DATESTYLE TO 'ISO' [42001-77]
        at org.h2.message.Message.getSQLException(Message.java:103)
        at org.h2.message.Message.getSQLException(Message.java:114)
        at org.h2.message.Message.getSyntaxError(Message.java:139)
=====>  at org.h2.command.Parser.read(Parser.java:2437)
        at org.h2.command.Parser.parseSet(Parser.java:4001)
        at org.h2.command.Parser.parsePrepared(Parser.java:396)
###########################
src/main/org/h2/command/Parser.java#4001


private void read(String expected) throws SQLException { 
if (!expected.equals(currentToken) || currentTokenQuoted) { <===== error  (line 
2436)
throw Message.getSyntaxError(sqlCommand, parseIndex, expected); 
} 
read(); 
}  
private boolean readIf(String token) throws SQLException { 
if (token.equals(currentToken) && !currentTokenQuoted) {  <====line 2443. This 
statement should be used in line 2436.
read(); 
return true; 
} 


```

Original comment by `effie.ba...@gmail.com` on 4 Sep 2008 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
Upon further investigation I believe it's down to how "set" is treated.

SET [ SESSION | LOCAL ] configuration_parameter { TO | = } {
 value | 'value' | DEFAULT }


'value' isn't handled by H2
```

Original comment by `effie.ba...@gmail.com` on 4 Sep 2008 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
we hacked the quotes issue to resolve the above and immediately after ran into 
another problem - 
SHOW client_encoding

org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement SHOW[*] 
CLIENT_ENCODING ; expected SELECT, SET, SAVEPOINT, SCRIPT, SHUTDOWN, {; SQL 
statement:
SHOW client_encoding [42001-77]



at org.h2.message.Message.getSQLException(Message.java:103)
        at org.h2.message.Message.getSQLException(Message.java:114)
        at org.h2.message.Message.getSyntaxError(Message.java:139)
        at org.h2.command.Parser.getSyntaxError(Parser.java:478)
        at org.h2.command.Parser.parsePrepared(Parser.java:461)
        at org.h2.command.Parser.parse(Parser.java:290)
        at org.h2.command.Parser.parse(Parser.java:266)
        at org.h2.command.Parser.prepareCommand(Parser.java:234)
        at org.h2.engine.Session.prepareLocal(Session.java:285)
        at org.h2.engine.Session.prepareCommand(Session.java:246)



```

Original comment by `effie.ba...@gmail.com` on 4 Sep 2008 at 8:31

**Comment by GoogleCodeExporter** [comment]
```
At the moment psycopg2 is not supported. This library executes SQL statements 
that H2
doesn't understand at the moment. As soon as I have time, I will analyze what is
required and implement the missing features.

```

Original comment by `thomas.t...@gmail.com` on 6 Sep 2008 at 4:16
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

The two problems should be fixed in todays release, but I don't know if 
psycopg2 will
work now. Could you please test it?

Regards,
Thomas
```

Original comment by `thomas.t...@gmail.com` on 26 Sep 2008 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Please re-open if there are additional problems.
```

Original comment by `thomas.t...@gmail.com` on 4 Oct 2008 at 2:06
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
>>> con = psycopg2.connect("dbname='blog' user='blog' password='blog'
host='127.0.0.1' port='5435'")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.OperationalError: can't fetch default_isolation_level

h2 -trace:
Connect
Init
SSLRequest
Init
StartupMessage
 version 196608 (3.0)
 param user=blog
 param database=blog
PasswordMessage
Query
SET DATESTYLE TO 'ISO';
Check command tag: SET DATESTYLE TO 'ISO'
Query
SHOW client_encoding;
Check command tag: SHOW CLIENT_ENCODING
Query
SHOW default_transaction_isolation;
org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "SELECT "; erwartet 
"TOP,
LIMIT, DISTINCT, ALL, *, NOT, EXISTS"
Syntax error in SQL statement "SELECT "; expected "TOP, LIMIT, DISTINCT, ALL, 
*, NOT,
EXISTS"; SQL statement:
SHOW default_transaction_isolation [42001-127]
        at org.h2.message.Message.getSQLException(Message.java:110)
        at org.h2.message.Message.getSQLException(Message.java:121)
        at org.h2.message.Message.getSyntaxError(Message.java:146)
        at org.h2.command.Parser.getSyntaxError(Parser.java:477)
        at org.h2.command.Parser.readTerm(Parser.java:2361)
        at org.h2.command.Parser.readFactor(Parser.java:1850)
        at org.h2.command.Parser.readSum(Parser.java:1837)
        at org.h2.command.Parser.readConcat(Parser.java:1810)
        at org.h2.command.Parser.readCondition(Parser.java:1681)
        at org.h2.command.Parser.readAnd(Parser.java:1662)
        at org.h2.command.Parser.readExpression(Parser.java:1654)
        at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:1569)
        at org.h2.command.Parser.parseSelectSimple(Parser.java:1599)
        at org.h2.command.Parser.parseSelectSub(Parser.java:1504)
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1349)
        at org.h2.command.Parser.parseSelect(Parser.java:1337)
        at org.h2.command.Parser.parsePrepared(Parser.java:395)
        at org.h2.command.Parser.parse(Parser.java:291)
        at org.h2.command.Parser.parse(Parser.java:267)
        at org.h2.command.Parser.prepare(Parser.java:205)
        at org.h2.engine.Session.prepare(Session.java:402)
        at org.h2.engine.Session.prepare(Session.java:389)
        at org.h2.command.Parser.prepare(Parser.java:835)
        at org.h2.command.Parser.parseShow(Parser.java:831)
        at org.h2.command.Parser.parsePrepared(Parser.java:405)
        at org.h2.command.Parser.parse(Parser.java:291)
        at org.h2.command.Parser.parse(Parser.java:263)
        at org.h2.command.Parser.prepareCommand(Parser.java:235)
        at org.h2.engine.Session.prepareLocal(Session.java:417)
        at org.h2.engine.Session.prepareCommand(Session.java:378)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:163)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:151)
        at org.h2.server.pg.PgServerThread.process(PgServerThread.java:342)
        at org.h2.server.pg.PgServerThread.run(PgServerThread.java:78)
        at java.lang.Thread.run(Thread.java:636)
Terminate
Close
Disconnect
Close


```

Original comment by `Stupid2n...@gmail.com` on 24 Jan 2010 at 5:39

**Comment by GoogleCodeExporter** [comment]
```
Hi,

This is now fixed in the trunk. 

Regards,
Thomas
```

Original comment by `thomas.t...@gmail.com` on 25 Jan 2010 at 7:23
