### ISSUE TITLE
IN Query Performance

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#343]
```

What steps will reproduce the problem?
(simple SQL scripts or simple standalone applications are preferred)

1.  The performance of a query that uses an IN sub-query with a function is 
substantially slower then a table join, or two queries.

In my example:

This query took about 60 seconds:
SELECT ID, geom
FROM TESTDATA
WHERE ID IN (
SELECT CAST (HATBOX_JOIN_ID AS INT)
FROM
HATBOX_MBR_INTERSECTS_ENV('PUBLIC', 'TESTDATA', -139.17094658129298,
-113.94051433313055, 44.17730198523503, 64.12298153276885));


However re-writing the query as a table join takes < 1 sec.
SELECT a."ID",a."geom" as "geom" FROM "TESTDATA" a
INNER JOIN
(SELECT CAST (HATBOX_JOIN_ID AS INT)  as id
FROM
HATBOX_MBR_INTERSECTS_ENV('PUBLIC', 'TESTDATA', -139.17094658129298,
-113.94051433313055, 44.17730198523503, 64.12298153276885)
) b ON a."ID" = b.id ;

Also if the query is executed in two steps it takes < 1sec:

CREATE TABLE TEMP AS SELECT CAST (HATBOX_JOIN_ID AS INT) as id
FROM HATBOX_MBR_INTERSECTS_ENV('PUBLIC', 'TESTDATA', -139.17094658129298,
-113.94051433313055, 44.17730198523503, 64.12298153276885;
SELECT ID, geom
FROM TESTDATA
WHERE ID IN ( SELECT ID FROM TEMP ) ;

2.  Discussion from the mailing list:
http://groups.google.com/group/h2-database/browse_thread/thread/2c72baec88db63d5
/13c3b25505ce4987?lnk=gst&q=H2+In+Query+Performance


3. Peter has provided a sample application that demonstrates the problem 
available here:
http://groups.google.com/group/h2-database/attach/5f2a6de5c6588b4f/InListTest.ja
va?part=2&view=1


What version of the product are you using? On what operating system, file
system, and virtual machine?

H2 Version: 1.3.159 
Java Version: 1.6
Windows XP

Do you know a workaround?

Use a Table Join instance of an IN statement.


```

Original issue reported on code.google.com by `ego...@refractions.net` on 8 Sep 2011 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Could you run a profiling tool to find out what is going on? For example the 
built-in profiler:

http://h2database.com/html/performance.html#built_in_profiler

Regards,
Thomas

```

Original comment by `thomas.t...@gmail.com` on 11 Sep 2011 at 3:00

**Comment by GoogleCodeExporter** [comment]
```

Running the profiler on the simple example provided by Peter:

count = 5000;
Profiler prof = new Profiler();
prof.startCollecting();
ResultSet rs = stmt.executeQuery("select ID from IN_LIST_TABLE where ID IN 
(select ID from PUBLIC.IN_LIST_TEST(" + count + "))");
rs.close();
prof.stopCollecting();

Results in the following:

Profiler: top 3 stack trace(s) of 20500 ms [build-159]:
272/5224 (5%):
at org.h2.util.ValueHashMap.rehash(ValueHashMap.java:48)
at org.h2.util.HashBase.checkSizePut(HashBase.java:78)
at org.h2.util.ValueHashMap.put(ValueHashMap.java:64)
at org.h2.result.LocalResult.containsDistinct(LocalResult.java:201)
at org.h2.expression.ConditionInSelect.getValue(ConditionInSelect.java:68)
at org.h2.expression.Expression.getBooleanValue(Expression.java:180)
at org.h2.command.dml.Select.queryFlat(Select.java:514)
at org.h2.command.dml.Select.queryWithoutCache(Select.java:617)
at org.h2.command.dml.Query.query(Query.java:298)
at org.h2.command.dml.Query.query(Query.java:268)
at org.h2.command.dml.Query.query(Query.java:37)
at org.h2.command.CommandContainer.query(CommandContainer.java:80)
at org.h2.command.Command.executeQuery(Command.java:181)
at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:76)
at FunctionTest.main(FunctionTest.java:88)
251/5224 (4%):
at org.h2.util.ValueHashMap.put(ValueHashMap.java:64)
at org.h2.result.LocalResult.containsDistinct(LocalResult.java:201)
at org.h2.expression.ConditionInSelect.getValue(ConditionInSelect.java:68)
at org.h2.expression.Expression.getBooleanValue(Expression.java:180)
at org.h2.command.dml.Select.queryFlat(Select.java:514)
at org.h2.command.dml.Select.queryWithoutCache(Select.java:617)
at org.h2.command.dml.Query.query(Query.java:298)
at org.h2.command.dml.Query.query(Query.java:268)
at org.h2.command.dml.Query.query(Query.java:37)
at org.h2.command.CommandContainer.query(CommandContainer.java:80)
at org.h2.command.Command.executeQuery(Command.java:181)
at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:76)
at FunctionTest.main(FunctionTest.java:88)
243/5224 (4%):
at java.util.ArrayList.get(ArrayList.java:322)
at org.h2.result.LocalResult.next(LocalResult.java:231)
at org.h2.index.FunctionCursor.next(FunctionCursor.java:44)
at org.h2.index.IndexCursor.next(IndexCursor.java:235)
at org.h2.table.TableFilter.next(TableFilter.java:352)
at org.h2.command.dml.Select.queryFlat(Select.java:512)
at org.h2.command.dml.Select.queryWithoutCache(Select.java:617)
at org.h2.command.dml.Query.query(Query.java:298)
at org.h2.command.dml.Query.query(Query.java:268)
at org.h2.expression.ConditionInSelect.getValue(ConditionInSelect.java:45)
at org.h2.expression.Expression.getBooleanValue(Expression.java:180)
at org.h2.command.dml.Select.queryFlat(Select.java:514)
at org.h2.command.dml.Select.queryWithoutCache(Select.java:617)
at org.h2.command.dml.Query.query(Query.java:298)
at org.h2.command.dml.Query.query(Query.java:268)
at org.h2.command.dml.Query.query(Query.java:37)
at org.h2.command.CommandContainer.query(CommandContainer.java:80)
at org.h2.command.Command.executeQuery(Command.java:181)
at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:76)
at FunctionTest.main(FunctionTest.java:88)
packages:
23%: org.h2.result
18%: org.h2.util
12%: 
.


I've attached the sample java file used to produce the above output.

```

Original comment by `ego...@refractions.net` on 13 Sep 2011 at 4:01

**Comment by GoogleCodeExporter** [comment]
```
Hi,

This is not a bug. The function is called each time because it is not declared 
as beeing deterministic. Simply make it deterministic:

stmt.execute("create alias if not exists IN_LIST_TEST deterministic for \""+
    FunctionTest.class.getName()+".test\"");

// normal
// Profiler: top 3 stack trace(s) of 10241 ms [build-160]:
// IN_LIST_TEST Excecutions: 5003
// IN_LIST_TEST Resultset next() Excecutions: 25020003

// deterministic
// Profiler: top 3 stack trace(s) of 5977 ms [build-160]:
// IN_LIST_TEST Excecutions: 3
// IN_LIST_TEST Resultset next() Excecutions: 15003

```

Original comment by `thomas.t...@gmail.com` on 22 Sep 2011 at 5:45
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
Even if I make the sample function deterministic the query time is still 10x 
longer than if I re-write it as a join.

Deterministic function the query:
select ID from IN_LIST_TABLE where ID IN (select ID from 
PUBLIC.IN_LIST_TEST(5000))
Takes about 10 sec.

Whereas a join takes < 1 sec:
Select a.ID from IN_LIST_TABLE as a,  (select ID from 
PUBLIC.IN_LIST_TEST(5000)) as b where a.id = b.id;

I believe this is still a issue because the older version 1.1.119 of H2 
performs both queries quickly:
IN: 0.05 sec
JOIN: 0.114 sec

Thanks.
```

Original comment by `ego...@refractions.net` on 22 Sep 2011 at 10:43
