### ISSUE TITLE
Table-to-table INSERT is impractically slow with some indexed columns

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#391]
```
What steps will reproduce the problem?

drop table test2, test1;
create table test1 (a1 identity);
create table test2 (a2 identity);
@LOOP 30000 insert into test2 values(?); -- insert #1, < 0.5 seconds
insert into test1 (a1) select a2 from test2; -- insert #2, between 8 and 30 
seconds

What is the expected output?

INSERT #1 and INSERT #1 would have simliar duration.

What do you see instead?

INSERT #2 takes 20-80 times longer than INSERT #1, even though there are only 
30000 rows involved.

What version of the product are you using? On what operating system, file
system, and virtual machine?

H2 1.3.166. Debian 6, Ubuntu Lucid & Mac OS X 10.7.3 (default installations).

Do you know a workaround?

insert into test1 (a1) sorted select a2 from test2;

Unfortunately, this workaround is ineffective when there are other indexed 
columns involved in the destination table.

What is your use case, meaning why do you need this feature?

INSERT is important to my application :)

How important/urgent is the problem for you?

It makes it impossible for me to work with tables larger than a few thousand 
rows, and unfortunately I need to demonstrate a bioinformatics project with 
tens of millions of rows. I have some laborious manual workarounds (drop 
columns/indices from the destination tables, then recreate them after insert). 
So it is critical but also I can live with it for another week until the system 
goes standalone.

Please provide any additional information below.

Frequent stack traces:

"H2 Console thread" prio=5 tid=7fdffc19b800 nid=0x1177ac000 runnable [1177aa000]
   java.lang.Thread.State: RUNNABLE
    at org.h2.store.PageStore.checkpoint(PageStore.java:443)
    - locked <7b8b83df8> (a org.h2.store.PageStore)
    at org.h2.store.PageStore.commit(PageStore.java:1433)
    - locked <7b8b83df8> (a org.h2.store.PageStore)
    at org.h2.engine.Database.commit(Database.java:1767)
    - locked <7b8b65850> (a org.h2.engine.Database)
    at org.h2.engine.Session.commit(Session.java:450)
    at org.h2.schema.Sequence.flush(Sequence.java:134)
    - locked <7b8b80300> (a org.h2.engine.Session)
    - locked <7b8f666d8> (a org.h2.schema.Sequence)
    at org.h2.table.Column.updateSequenceIfRequired(Column.java:337)
    at org.h2.table.Column.validateConvertUpdateSequence(Column.java:319)
    at org.h2.table.Table.validateConvertUpdateSequence(Table.java:680)
    at org.h2.command.dml.Insert.addRow(Insert.java:159)
    at org.h2.command.dml.Insert.insertRows(Insert.java:137)
    at org.h2.command.dml.Insert.update(Insert.java:84)
    at org.h2.command.CommandContainer.update(CommandContainer.java:73)
    at org.h2.command.Command.executeUpdate(Command.java:226)
    - locked <7b8b65850> (a org.h2.engine.Database)
    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
    - locked <7b8b99c00> (a org.h2.engine.Session)
    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
    at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
    at org.h2.server.web.WebApp.query(WebApp.java:1001)
    at org.h2.server.web.WebApp$1.next(WebApp.java:964)
    at org.h2.server.web.WebApp$1.next(WebApp.java:967)
    at org.h2.server.web.WebThread.process(WebThread.java:166)
    at org.h2.server.web.WebThread.run(WebThread.java:93)
    at java.lang.Thread.run(Thread.java:680)


"H2 Console thread" prio=5 tid=7fdffc19b800 nid=0x1177ac000 runnable [1177ab000]
   java.lang.Thread.State: RUNNABLE
    at java.io.FileDescriptor.sync(Native Method)
    at org.h2.store.fs.FileDisk.force(FilePathDisk.java:387)
    at org.h2.store.FileStore.sync(FileStore.java:413)
    at org.h2.store.PageStore.writeVariableHeader(PageStore.java:943)
    at org.h2.store.PageStore.setLogFirstPage(PageStore.java:937)
    at org.h2.store.PageLog.removeUntil(PageLog.java:702)
    at org.h2.store.PageStore.checkpoint(PageStore.java:430)
    - locked <7b8b83df8> (a org.h2.store.PageStore)
    at org.h2.store.PageStore.commit(PageStore.java:1433)
    - locked <7b8b83df8> (a org.h2.store.PageStore)
    at org.h2.engine.Database.commit(Database.java:1767)
    - locked <7b8b65850> (a org.h2.engine.Database)
    at org.h2.engine.Session.commit(Session.java:450)
    at org.h2.schema.Sequence.flush(Sequence.java:134)
    - locked <7b8b80300> (a org.h2.engine.Session)
    - locked <7b8f666d8> (a org.h2.schema.Sequence)
    at org.h2.table.Column.updateSequenceIfRequired(Column.java:337)
    at org.h2.table.Column.validateConvertUpdateSequence(Column.java:319)
    at org.h2.table.Table.validateConvertUpdateSequence(Table.java:680)
    at org.h2.command.dml.Insert.addRow(Insert.java:159)
    at org.h2.command.dml.Insert.insertRows(Insert.java:137)
    at org.h2.command.dml.Insert.update(Insert.java:84)
    at org.h2.command.CommandContainer.update(CommandContainer.java:73)
    at org.h2.command.Command.executeUpdate(Command.java:226)
    - locked <7b8b65850> (a org.h2.engine.Database)
    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
    - locked <7b8b99c00> (a org.h2.engine.Session)
    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
    at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
    at org.h2.server.web.WebApp.query(WebApp.java:1001)
    at org.h2.server.web.WebApp$1.next(WebApp.java:964)
    at org.h2.server.web.WebApp$1.next(WebApp.java:967)
    at org.h2.server.web.WebThread.process(WebThread.java:166)
    at org.h2.server.web.WebThread.run(WebThread.java:93)
    at java.lang.Thread.run(Thread.java:680)

```

Original issue reported on code.google.com by `jndeven...@gmail.com` on 13 Apr 2012 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I can't reproduce this, what database URL do you use? I get:

@LOOP 30000 insert into test2 values(?);
855 ms: 30000 * (Prepared) (i) insert into test2 values(?)

insert into test1 (a1) select a2 from test2;
Update count: 30000
(587 ms)

Regards,
Thomas
```

Original comment by `thomas.t...@gmail.com` on 9 May 2012 at 6:44
- Changed state: **WorksForMe**

**Comment by GoogleCodeExporter** [comment]
```
Hi Thomas,

I tried some URLs, it's still a huge problem for me.

But in embedded mode, if I run the test many times with 30000 inserts, I get 
good results like yours. Sometimes I get slow results, but perhaps it’s just 
the garbage collector. I've modified the test case to have two indices.

At 50000 inserts, insert #2 is faster than insert #1. If I try 60000 inserts, 
insert #2 becomes 10x slower than insert #1. If I try 70000 inserts, the 
slowdown is 30x or worse.

-- java -jar h2-1.3.166.jar
-- http://localhost:8082
-- jdbc:h2:~/test

drop table if exists test2, test1;
create table test1 (a1 identity);
create table test2 (a2 identity);
@LOOP 50000 insert into test2 values(?); -- insert #1
-- 832 ms: 60000 * (Prepared) (i) insert into test2 values(?)
insert into test1 (a1) select a2 from test2; -- insert #2
-- Update count: 50000
-- (606 ms) -- fast

drop table if exists test2, test1;
create table test1 (a1 identity);
create table test2 (a2 identity);
@LOOP 60000 insert into test2 values(?); -- insert #1
-- 947 ms: 60000 * (Prepared) (i) insert into test2 values(?)
insert into test1 (a1) select a2 from test2; -- insert #2
-- Update count: 60000
-- (11339 ms - 21123 ms) -- slow

drop table if exists test2, test1;
create table test1 (a1 identity);
create table test2 (a2 identity);
@LOOP 70000 insert into test2 values(?);
-- 1161 ms: 70000 * (Prepared) (i) insert into test2 values(?)
insert into test1 (a1) select a2 from test2;
-- (36212 ms - 58420 ms) -- very slow

If I use a non-unique index with low-cardinality, this problem appears to be 
gone:

drop table if exists test2, test1;
create table test1 (a1 int);
create index a1 on test1(a1);
create table test2 (a2 identity);
@LOOP 80000 insert into test2 values(?); -- insert #1
-- 1295 ms: 80000 * (Prepared) (i) insert into test2 values(?)
insert into test1 (a1) select 1 from test2; -- insert #2
-- Update count: 80000
-- (392 ms) -- fast

```

Original comment by `jndeven...@gmail.com` on 9 May 2012 at 10:22
