### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: File corrupted while reading record: "wrong checksum".

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#429]
```
I use version h2-1.3.169, and use the recovery tool,  is not recovery 

File corrupted while reading record: "wrong checksum". Possible solution: use 
the recovery tool [90030-169] 90030/90030 (Help)
org.h2.jdbc.JdbcSQLException: File corrupted while reading record: "wrong 
checksum". Possible solution: use the recovery tool [90030-169] 
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) 
    at org.h2.message.DbException.get(DbException.java:169) 
    at org.h2.message.DbException.get(DbException.java:146) 
    at org.h2.store.PageStore.getPage(PageStore.java:743) 
    at org.h2.store.PageStore.getFreeList(PageStore.java:1083) 
    at org.h2.store.PageStore.getFreeListForPage(PageStore.java:1067) 
    at org.h2.store.PageStore.isUsed(PageStore.java:1114) 
    at org.h2.store.PageStore.checkpoint(PageStore.java:448) 
    at org.h2.store.PageStore.openForWriting(PageStore.java:383) 
    at org.h2.store.PageStore.openExisting(PageStore.java:366) 
    at org.h2.store.PageStore.open(PageStore.java:285) 
    at org.h2.engine.Database.getPageStore(Database.java:2118) 
    at org.h2.engine.Database.open(Database.java:577) 
    at org.h2.engine.Database.openDatabase(Database.java:222) 
    at org.h2.engine.Database.<init>(Database.java:217) 
    at org.h2.engine.Engine.openSession(Engine.java:56) 
    at org.h2.engine.Engine.openSession(Engine.java:159) 
    at org.h2.engine.Engine.createSessionAndValidate(Engine.java:138) 
    at org.h2.engine.Engine.createSession(Engine.java:121) 
    at org.h2.engine.Engine.createSession(Engine.java:28) 
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:305) 
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:109) 
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93) 
    at org.h2.Driver.connect(Driver.java:72) 
    at org.h2.server.web.WebServer.getConnection(WebServer.java:645) 
    at org.h2.server.web.WebApp.login(WebApp.java:899) 
    at org.h2.server.web.WebApp.process(WebApp.java:205) 
    at org.h2.server.web.WebApp.processRequest(WebApp.java:164) 
    at org.h2.server.web.WebThread.process(WebThread.java:137) 
    at org.h2.server.web.WebThread.run(WebThread.java:93) 
    at java.lang.Thread.run(Unknown Source) 
```

Original issue reported on code.google.com by `lyc...@gmail.com` on 30 Nov 2012 at 3:35

**Comment by GoogleCodeExporter** [comment]
```
Wrong checksum means the file is corrupt (some other application wrote to it, 
or media failure).

- What is your database URL?
- Did you use LOG=0 or LOG=1? Did you read the FAQ about it?
- Did the system ever run out of disk space?
- Could you send the full stack trace of the exception including message text?
- Did you use SHUTDOWN DEFRAG or the database setting DEFRAG_ALWAYS with H2 
version 1.3.159 or older?
- How many connections does your application use concurrently?
- Do you use temporary tables?
- With which version of H2 was this database created?
    You can find it out using:
    select * from information_schema.settings where name='CREATE_BUILD'
    or have a look in the SQL script created by the recover tool.
- Did the application run out of memory (once, or multiple times)?
- Do you use any settings or special features (for example cache settings,
    two phase commit, linked tables)?
- Do you use any H2-specific system properties?
- Is the application multi-threaded?
- What operating system, file system, and virtual machine
    (java -version) do you use?
- How did you start the Java process (java -Xmx... and so on)?
- Is it (or was it at some point) a networked file system?
- How big is the database (file sizes)?
- How much heap memory does the Java process have?
- Is the database usually closed normally, or is process terminated
    forcefully or the computer switched off?
- Is it possible to reproduce this problem using a fresh database
    (sometimes, or always)?
- Are there any other exceptions (maybe in the .trace.db file)?
    Could you send them please?
- Do you still have any .trace.db files, and if yes could you send them?
- Could you send the .h2.db file where this exception occurs?
```

Original comment by `thomas.t...@gmail.com` on 30 Nov 2012 at 6:54
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
jdbc:h2:file:config/fg
```

Original comment by `lyc...@gmail.com` on 1 Dec 2012 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
yygl.trace.db
```

Original comment by `lyc...@gmail.com` on 1 Dec 2012 at 1:24
