### ISSUE TITLE
error 50000-104 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#48]
```
I'm getting the following exception when running some tests:
com.intecbilling.replib.cache.CacheException: org.h2.jdbc.JdbcSQLException:
General error: java.lang.ArrayIndexOutOfBoundsException: i=4 size=1; SQL
statement:
select i.folder, i.name from ITEM i where i.repository=? and ((i.type=? or
i.type=?) and i.name like ? and regexp_replace(i.folder,
'.*[CMFact|PEFact]/', '') in (select cr_1.name from class_reference cr_1
join item i_1 on i_1.id=cr_1.id where i_1.type in (?, ?) and i_1.name like
?)) [50000-104]
    at
com.intecbilling.replib.cache.CacheItemSearchProcessor.execute(CacheItemSearchPr
ocessor.java:80)
    at com.intecbilling.replib.cache.Cache.findByCriteria(Cache.java:2321)
    at
com.intecbilling.replib.cache.CacheTest.testFindBySxpVariableCriteria(CacheTest.
java:1625)
Caused by: org.h2.jdbc.JdbcSQLException: General error:
java.lang.ArrayIndexOutOfBoundsException: i=4 size=1; SQL statement:
select i.folder, i.name from ITEM i where i.repository=? and ((i.type=? or
i.type=?) and i.name like ? and regexp_replace(i.folder,
'.*[CMFact|PEFact]/', '') in (select cr_1.name from class_reference cr_1
join item i_1 on i_1.id=cr_1.id where i_1.type in (?, ?) and i_1.name like
?)) [50000-104]
    at org.h2.message.Message.getSQLException(Message.java:103)
    at org.h2.message.Message.convert(Message.java:257)
    at org.h2.message.Message.convert(Message.java:226)
    at org.h2.command.Command.executeQueryLocal(Command.java:143)
    at org.h2.command.Command.executeQuery(Command.java:122)
    at
org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)
    at
com.adc.profiler.sql.ProfilePreparedStatement.executeQuery(ProfilePreparedStatem
ent.java:174)
    at com.intecbilling.replib.cache.query.Query.execute(Query.java:226)
    at
com.intecbilling.replib.cache.CacheItemSearchProcessor.execute(CacheItemSearchPr
ocessor.java:77)
    ... 24 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: i=4 size=1
    at org.h2.util.ObjectArray.throwException(ObjectArray.java:56)
    at org.h2.util.ObjectArray.get(ObjectArray.java:79)
    at org.h2.index.ViewIndex.find(ViewIndex.java:161)
    at org.h2.table.TableFilter.next(TableFilter.java:294)
    at org.h2.table.TableFilter.next(TableFilter.java:349)
    at org.h2.command.dml.Select.queryFlat(Select.java:492)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:560)
    at org.h2.command.dml.Query.query(Query.java:233)
    at org.h2.command.CommandContainer.query(CommandContainer.java:81)
    at org.h2.command.Command.executeQueryLocal(Command.java:141)
    ... 29 more
... Removed 22 stack frames

I'm hoping the stack trace is useful for diagnosis, because unfortunately I
can't produce a simple test to produce the problem.  Running the query by
itself works OK.  It appears to be the sequence of prior operations that
cause the failure.  

This error was obtained with 1.1.104.  I was trying to use 1.1.104 and
found that some queries like the one above weren't returning the same
results as they used to with 1.0.71.  But when I ran the individual queries
with 1.1.104 the results looked right.  Once again, prior operations seemed
to mess up the results in some way that doesn't seem to be easy to reproduce.

```

Original issue reported on code.google.com by `bwatsonl...@gmail.com` on 19 Dec 2008 at 1:58

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed in version 1.1.105; could you verify this please?
```

Original comment by `thomas.t...@gmail.com` on 19 Dec 2008 at 3:04
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I'm getting the same error with 1.1.105. 

The stack trace is:
Caused by: org.h2.jdbc.JdbcSQLException: General error:
java.lang.ArrayIndexOutOfBoundsException: i=2 size=2; SQL statement:
select expandedit0_.mbs_item_id as mbs8_1_, expandedit0_.id as id1_, 
expandedit0_.id
as id15_0_, expandedit0_.sb_version as sb2_15_0_, expandedit0_.unique_id as
unique3_15_0_, expandedit0_.description as descript4_15_0_,
expandedit0_.description_start_date as descript5_15_0_,
expandedit0_.gs_classification_id as gs7_15_0_, expandedit0_.mbs_item_id as
mbs8_15_0_, expandedit0_.ns_classification_id as ns9_15_0_,
expandedit0_.mbs_operation_group_id as mbs10_15_0_, expandedit0_.severity_value 
as
severity6_15_0_ from mbs_expanded_items expandedit0_ where 
expandedit0_.mbs_item_id
in (select mbsitem3_.id from gs_operation_histories generalsur0_ inner join
br_operation_desc_mbs expandedit1_ on 
generalsur0_.id=expandedit1_.operation_desc_id
inner join mbs_expanded_items mbsexpande2_ on
expandedit1_.mbs_expanded_item_id=mbsexpande2_.id inner join mbs_full_items 
mbsitem3_
on mbsexpande2_.mbs_item_id=mbsitem3_.id inner join
mbs_generalsurgery_classifications generalsur4_ on
generalsur0_.classification_id=generalsur4_.id where generalsur0_.unit_id=? and
generalsur0_.last_used>=? and (mbsexpande2_.id in (? , ? , ?))) [50000-105]
    at org.h2.message.Message.getSQLException(Message.java:103)
    at org.h2.message.Message.convert(Message.java:274)
    at org.h2.message.Message.convert(Message.java:243)
    at org.h2.command.Command.executeQueryLocal(Command.java:143)
    at org.h2.command.Command.executeQuery(Command.java:122)
    at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)
    at
org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPrepa
redStatement.java:93)
    at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:186)
    at org.hibernate.loader.Loader.getResultSet(Loader.java:1787)
    at org.hibernate.loader.Loader.doQuery(Loader.java:674)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:236)
    at org.hibernate.loader.Loader.loadCollectionSubselect(Loader.java:2066)
    at
org.hibernate.loader.collection.SubselectOneToManyLoader.initialize(SubselectOne
ToManyLoader.java:58)
    at
org.hibernate.persister.collection.AbstractCollectionPersister.initialize(Abstra
ctCollectionPersister.java:565)
    at
org.hibernate.event.def.DefaultInitializeCollectionEventListener.onInitializeCol
lection(DefaultInitializeCollectionEventListener.java:63)
    at org.hibernate.impl.SessionImpl.initializeCollection(SessionImpl.java:1716)
    at
org.hibernate.collection.AbstractPersistentCollection.forceInitialization(Abstra
ctPersistentCollection.java:454)
    at
org.hibernate.engine.StatefulPersistenceContext.initializeNonLazyCollections(Sta
tefulPersistenceContext.java:844)
    at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:241)
    at org.hibernate.loader.Loader.doList(Loader.java:2213)
    at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2104)
    at org.hibernate.loader.Loader.list(Loader.java:2099)
    at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:378)
    at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:338)
    at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:172)
    at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1121)
    at org.hibernate.impl.QueryImpl.list(QueryImpl.java:79)
    at
au.com.surgbase.dao.hibernate.HibernateDAOPipeline$2.doInHibernate(HibernateDAOP
ipeline.java:232)
    at
org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate
.java:419)
    ... 30 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: i=2 size=2
    at org.h2.util.ObjectArray.throwException(ObjectArray.java:56)
    at org.h2.util.ObjectArray.get(ObjectArray.java:79)
    at org.h2.index.ViewIndex.find(ViewIndex.java:159)
    at org.h2.table.TableFilter.next(TableFilter.java:295)
    at org.h2.command.dml.Select.queryFlat(Select.java:492)
    at org.h2.command.dml.Select.queryWithoutCache(Select.java:560)
    at org.h2.command.dml.Query.query(Query.java:233)
    at org.h2.command.CommandContainer.query(CommandContainer.java:81)
    at org.h2.command.Command.executeQueryLocal(Command.java:141)
    ... 55 more

What it looks like is Hibernate is using a subselect to fetch a collection (one 
to
many) and h2 is rewriting the query and replacing the parameters in the "IN 
(x,x,x)"
clause with actual values. The part of h2 that is throwing the excepting is 
still
trying to set those parameters, even though they don't now exist.

Original query:
select expandedit0_.mbs_item_id as mbs8_1_, expandedit0_.id as id1_, 
expandedit0_.id
as id15_0_, expandedit0_.sb_version as sb2_15_0_, expandedit0_.unique_id as
unique3_15_0_, expandedit0_.description as descript4_15_0_,
expandedit0_.description_start_date as descript5_15_0_,
expandedit0_.gs_classification_id as gs7_15_0_, expandedit0_.mbs_item_id as
mbs8_15_0_, expandedit0_.ns_classification_id as ns9_15_0_,
expandedit0_.mbs_operation_group_id as mbs10_15_0_, expandedit0_.severity_value 
as
severity6_15_0_ from mbs_expanded_items expandedit0_ where 
expandedit0_.mbs_item_id
in (select mbsitem3_.id from gs_operation_histories generalsur0_ inner join
br_operation_desc_mbs expandedit1_ on 
generalsur0_.id=expandedit1_.operation_desc_id
inner join mbs_expanded_items mbsexpande2_ on
expandedit1_.mbs_expanded_item_id=mbsexpande2_.id inner join mbs_full_items 
mbsitem3_
on mbsexpande2_.mbs_item_id=mbsitem3_.id inner join
mbs_generalsurgery_classifications generalsur4_ on
generalsur0_.classification_id=generalsur4_.id where generalsur0_.unit_id=? and
generalsur0_.last_used>=? and (mbsexpande2_.id in (? , ? , ?))) 
{1: 219039, 2: DATE '2006-02-01', 3: 11, 4: 44, 5: 87};

Rewritten query:
SELECT DISTINCT MBSITEM3_.ID AS TEMP_VIEW_244_X
FROM PUBLIC.GS_OPERATION_HISTORIES GENERALSUR0_ /* 
PUBLIC.FKC7054787A331F2D3_INDEX_9:
UNIT_ID = ?1 */ /* WHERE (GENERALSUR0_.UNIT_ID = ?1) AND 
(GENERALSUR0_.LAST_USED >=
?2) */
INNER JOIN PUBLIC.MBS_GENERALSURGERY_CLASSIFICATIONS GENERALSUR4_ /*
PUBLIC.PRIMARY_KEY_5C: ID = GENERALSUR0_.CLASSIFICATION_ID */ ON 1=1 /* WHERE
GENERALSUR0_.CLASSIFICATION_ID = GENERALSUR4_.ID */
INNER JOIN TABLE_DISTINCT(TEMP_VIEW_242_X BIGINT=(11, 44, 87)) TEMP_VIEW_243 /*
PUBLIC."" */ ON 1=1
INNER JOIN PUBLIC.MBS_EXPANDED_ITEMS MBSEXPANDE2_ /* PUBLIC.PRIMARY_KEY_F: ID =
TEMP_VIEW_243.TEMP_VIEW_242_X AND ID >= 11 AND ID <= 87 */ ON 1=1 /* WHERE
(MBSEXPANDE2_.ID IN(11, 44, 87)) AND (MBSEXPANDE2_.ID = 
TEMP_VIEW_243.TEMP_VIEW_242_X) */
INNER JOIN PUBLIC.BR_OPERATION_DESC_MBS EXPANDEDIT1_ /* PUBLIC.PRIMARY_KEY_D5:
MBS_EXPANDED_ITEM_ID = MBSEXPANDE2_.ID AND OPERATION_DESC_ID = GENERALSUR0_.ID 
*/ ON
1=1 /* WHERE (EXPANDEDIT1_.MBS_EXPANDED_ITEM_ID = MBSEXPANDE2_.ID) AND
(GENERALSUR0_.ID = EXPANDEDIT1_.OPERATION_DESC_ID) */
INNER JOIN PUBLIC.MBS_FULL_ITEMS MBSITEM3_ /* PUBLIC.PRIMARY_KEY_65: ID =
MBSEXPANDE2_.MBS_ITEM_ID */ ON 1=1 /* WHERE MBSEXPANDE2_.MBS_ITEM_ID = 
MBSITEM3_.ID */
INNER JOIN TABLE_DISTINCT(TEMP_VIEW_260_X BIGINT=(11, 44, 87)) TEMP_VIEW_261 /*
PUBLIC."": TEMP_VIEW_260_X = MBSEXPANDE2_.ID */ ON 1=1
WHERE (((GENERALSUR0_.UNIT_ID = ?1) AND (GENERALSUR0_.LAST_USED >= ?2)) AND
((MBSEXPANDE2_.ID = TEMP_VIEW_243.TEMP_VIEW_242_X) AND ((MBSEXPANDE2_.ID IN(11, 
44,
87)) AND (MBSEXPANDE2_.ID = TEMP_VIEW_261.TEMP_VIEW_260_X)))) AND
((GENERALSUR0_.CLASSIFICATION_ID = GENERALSUR4_.ID) AND 
((MBSEXPANDE2_.MBS_ITEM_ID =
MBSITEM3_.ID) AND ((EXPANDEDIT1_.MBS_EXPANDED_ITEM_ID = MBSEXPANDE2_.ID) AND
(GENERALSUR0_.ID = EXPANDEDIT1_.OPERATION_DESC_ID))))

(Notice the IN(11, 44, 87))


ViewIndex#public Cursor find(Session session, SearchRow first, SearchRow last) 
throws
SQLException {
        ObjectArray paramList = query.getParameters();
        for (int i = 0; originalParameters != null && i < originalParameters.size();
i++) {
            Parameter orig = (Parameter) originalParameters.get(i);
            int idx = orig.getIndex();
//Fails on the next line as IN(x,x,x) parameters don't exist in rewritten query.
            Parameter param = (Parameter) paramList.get(idx);
            Value value = orig.getValue(session);
            param.setValue(value);
        }


```

Original comment by `acambr...@gmail.com` on 26 Dec 2008 at 3:04

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your help! I have a simpler test case now:

drop table test;
create table test(id int primary key) as select 1;
@LOOP 10 select * from test t where t.id in (select t2.id from test t2 where 
t2.id in
(?, ?));

```

Original comment by `thomas.t...@gmail.com` on 30 Dec 2008 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed in version 1.1.106; could you verify this please?

```

Original comment by `thomas.t...@gmail.com` on 4 Jan 2009 at 1:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `thomas.t...@gmail.com` on 26 Jan 2009 at 5:43
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I have following error:

org.h2.jdbc.JdbcSQLException: General error:
java.lang.ArrayIndexOutOfBoundsException: i=0 size=0; SQL statement:
delete from spambox where MailFileName='159542811140_1589348_tm' [50000-116]
    at org.h2.message.Message.getSQLException(Message.java:105)
    at org.h2.message.Message.convert(Message.java:274)

h2 version h2-2009-07-18.zip
```

Original comment by `ardi.c...@gmail.com` on 22 Jul 2009 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
Could you post the complete error message and stack trace please?
```

Original comment by `thomas.t...@gmail.com` on 31 Jul 2009 at 6:25
