### ISSUE TITLE
java.lang.RuntimeException: rowCount expected N got M Tx.Iy [50000-164]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sagarswathi/h2database#612]
```
Notation:

N > M 
Tx: Table
Iy: Index

Excerpt from Stacktrace:
...
java.lang.RuntimeException: rowCount expected 18231 got 18196 T1995.I823
at org.h2.message.DbException.throwInternalError(DbException.java:228)
at org.h2.table.RegularTable.checkRowCount(RegularTable.java:169)
at org.h2.table.RegularTable.addRow(RegularTable.java:122)

...
```

Original issue reported on code.google.com by `hkatzlin...@gmail.com` on 14 Jul 2015 at 7:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `hkatzlin...@gmail.com` on 14 Jul 2015 at 7:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `hkatzlin...@gmail.com` on 14 Jul 2015 at 8:08

Attachments:
- [server_kathe.log](https://storage.googleapis.com/google-code-attachments/h2database/issue-612/comment-2/server_kathe.log)

**Comment by GoogleCodeExporter** [comment]
```
I'm sorry but I will close this issue, for multiple reasons:

Did you read the comment when you opened a new issue?

"
This project was migrated to Github.
Please report new issues here:
https://github.com/h2database/h2database/issues
"

Second, you are using an old version of H2 (1.3.164).

This looks like a corrupt database. To recover the data, use the tool 
org.h2.tools.Recover to create the SQL script file, and then re-create the 
database using this script. Does it work when you do this?

There is a known problem with version 1.3.171 and older: when using local 
temporary tables and not dropping them manually before closing the session, and 
then killing the process could result in a database that couldn't be opened.

```

Original comment by `thomas.t...@gmail.com` on 16 Jul 2015 at 6:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `thomas.t...@gmail.com` on 16 Jul 2015 at 6:08
- Changed state: **WorksForMe**

**Comment by GoogleCodeExporter** [comment]
```
The recovery tool does not work well and takes a lot of time. (DB-Size: ~ 1GB)

There are no local temporary tables within the database
```

Original comment by `hkatzlin...@gmail.com` on 14 Aug 2015 at 7:42
